# Generated by Django 4.0.4 on 2022-06-23 23:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import system.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('national_id', models.IntegerField(blank=True, null=True)),
                ('identification', models.ImageField(blank=True, null=True, upload_to=system.models.upload_to)),
                ('social_website', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_name', models.CharField(blank=True, choices=[('doctor', 'doctor'), ('patient', 'patient')], max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('gander', models.CharField(blank=True, choices=[('male', 'male'), ('famale', 'famale')], max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=system.models.upload_to)),
                ('type_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='system.type')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('patientDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patient_set', to='system.doctor')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='system.profile')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='system.profile'),
        ),
    ]
