# Generated by Django 4.0.4 on 2022-06-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'doctor')},
        ),
    ]
