# Generated by Django 4.0.4 on 2022-06-24 23:19

from django.db import migrations, models
import django.db.models.deletion
import system.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_remove_doctor_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='system.profile')),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('national_id', models.IntegerField(blank=True, null=True)),
                ('identification', models.ImageField(blank=True, null=True, upload_to=system.models.upload_to)),
                ('social_website', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('system.profile',),
        ),
    ]
