# Generated by Django 4.0.4 on 2022-06-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
    ]
