# Generated by Django 4.0.4 on 2022-06-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_pregnant_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_arabic', models.CharField(max_length=50, verbose_name='governorate_name_ar')),
                ('state_english', models.CharField(max_length=50, verbose_name='governorate_name_en')),
            ],
        ),
    ]
